apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sentinel
resources:
  - 00-namespace.yml
  - 01-zookeeper.yml
  - 02-kafka.yml
  - 03-elasticsearch.yml
  - 04-ollama.yml
  - 05-ingestion-service.yml
  - 06-processing-service.yml
  - 07-dashboard.yml
  - 08-prometheus.yml
  - 09-grafana.yml
  - 10-ingress.yml
